"""Chat DTOs (Data Transfer Objects)

This module defines DTOs for chat-related use cases.
DTOs are used to transfer data between layers (Presentation <-> Application).
They are separate from Domain Entities to maintain clean separation of concerns.
"""
from typing import Any, Literal

from pydantic import BaseModel, Field


class FilelistScreenContextDTO(BaseModel):
    """File list screen context DTO"""
    name: Literal["filelist"] = "filelist"


class EditScreenContextDTO(BaseModel):
    """Edit screen context DTO"""
    name: Literal["edit"] = "edit"
    filePath: str
    fileContent: str


class ChatContextDTO(BaseModel):
    """Chat context DTO

    Contains all contextual information for a chat request:
    - File system context (current path, file list)
    - File content (current file, attached files)
    - Conversation history
    - Active screen information
    """
    currentPath: str | None = None
    fileList: list[dict[str, Any]] | None = None
    currentFile: str | None = None
    currentFileContent: dict[str, str | None] | None = None
    attachedFileContent: list[dict[str, str]] | None = None
    conversationHistory: list[dict[str, Any]] | None = None
    activeScreen: FilelistScreenContextDTO | EditScreenContextDTO | None = Field(
        None, discriminator='name'
    )
    allFiles: list[dict[str, Any]] | None = None
    sendFileContextToLLM: bool | None = None


class ChatRequestDTO(BaseModel):
    """Chat request DTO

    Represents a chat request from the client.
    """
    message: str
    provider: str
    model: str
    context: ChatContextDTO | None = None
    client_id: str | None = None  # WebSocket client ID


class TokenUsageInfoDTO(BaseModel):
    """Token usage information DTO

    Used to inform the client about token usage and whether
    conversation summarization is recommended.
    """
    currentTokens: int  # Current conversation token count
    maxTokens: int  # Recommended max tokens
    usageRatio: float  # Usage ratio (0.0-1.0)
    needsSummary: bool  # Whether summarization is recommended

    # Actual token usage for billing
    inputTokens: int | None = None
    outputTokens: int | None = None
    totalTokens: int | None = None


class LLMCommandDTO(BaseModel):
    """LLM command DTO

    Represents a command generated by the LLM (e.g., file operations).
    """
    action: str
    title: str | None = None  # File name
    new_title: str | None = None  # New file name (for rename)
    content: str | None = None  # File content
    category: str | None = None  # Category (hierarchical path)
    tags: list[str] | None = None  # Tags

    # Line-based editing fields
    start_line: int | None = None  # Start line (1-based, inclusive)
    end_line: int | None = None  # End line (1-based, inclusive)


class ChatResponseDTO(BaseModel):
    """Chat response DTO

    Represents the response from a chat use case.
    """
    message: str
    commands: list[LLMCommandDTO] | None = None
    provider: str | None = None
    model: str | None = None
    historyCount: int | None = None
    tokenUsage: TokenUsageInfoDTO | None = None
    warning: str | None = None  # Warning messages (e.g., low tokens)
    error: str | None = None  # Error messages


# Mapper functions to convert between DTOs and Domain Entities

def chat_context_dto_to_domain(dto: ChatContextDTO | None):
    """Convert ChatContextDTO to Domain ChatContext

    Args:
        dto: ChatContextDTO or None

    Returns:
        Domain ChatContext or None
    """
    if not dto:
        return None

    from ...domain import ChatContext

    return ChatContext(
        currentPath=dto.currentPath,
        fileList=dto.fileList,
        currentFile=dto.currentFile,
        currentFileContent=dto.currentFileContent,
        attachedFileContent=dto.attachedFileContent,
        conversationHistory=dto.conversationHistory,
        activeScreen=dto.activeScreen,
        allFiles=dto.allFiles,
        sendFileContextToLLM=dto.sendFileContextToLLM
    )


def token_usage_domain_to_dto(domain_token_usage) -> TokenUsageInfoDTO:
    """Convert Domain TokenUsageInfo to DTO

    Args:
        domain_token_usage: Domain TokenUsageInfo

    Returns:
        TokenUsageInfoDTO
    """
    return TokenUsageInfoDTO(
        currentTokens=domain_token_usage.current_tokens,
        maxTokens=domain_token_usage.max_tokens,
        usageRatio=domain_token_usage.usage_ratio,
        needsSummary=domain_token_usage.needs_summary,
        inputTokens=domain_token_usage.input_tokens,
        outputTokens=domain_token_usage.output_tokens,
        totalTokens=domain_token_usage.total_tokens
    )


def llm_command_domain_to_dto(domain_command) -> LLMCommandDTO:
    """Convert Domain LLMCommand to DTO

    Args:
        domain_command: Domain LLMCommand

    Returns:
        LLMCommandDTO
    """
    return LLMCommandDTO(
        action=domain_command.action,
        title=domain_command.title,
        new_title=domain_command.new_title,
        content=domain_command.content,
        category=domain_command.category,
        tags=domain_command.tags,
        start_line=domain_command.start_line,
        end_line=domain_command.end_line
    )
