# Cloud Build 設定ファイル
# Cloud Run へのデプロイを自動化

steps:
  # ステップ1: Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/noteapp-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/noteapp-api:latest'
      - '.'

  # ステップ2: イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/noteapp-api:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/noteapp-api:latest'

  # ステップ3: Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'noteapp-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/noteapp-api:$SHORT_SHA'
      - '--region'
      - 'asia-northeast1'  # 東京リージョン
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # 公開API（認証はアプリ側で実装）
      - '--set-env-vars'
      - 'ENV=production,LOG_LEVEL=INFO,GCP_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,GOOGLE_CSE_API_KEY=GOOGLE_CSE_API_KEY:latest'

images:
  - 'gcr.io/$PROJECT_ID/noteapp-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/noteapp-api:latest'

timeout: '1200s'  # 20分
