"""
@file codes.py
@summary エラーコード定数
@responsibility アプリケーション全体で使用するエラーコードを定義
"""

# ==========================================
# 一般エラー
# ==========================================
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
NOT_FOUND = "NOT_FOUND"
FORBIDDEN = "FORBIDDEN"
UNAUTHORIZED = "UNAUTHORIZED"
BAD_REQUEST = "BAD_REQUEST"
CONFLICT = "CONFLICT"

# ==========================================
# 認証エラー
# ==========================================
AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
AUTH_DEVICE_NOT_FOUND = "AUTH_DEVICE_NOT_FOUND"
AUTH_OAUTH_ERROR = "AUTH_OAUTH_ERROR"
AUTH_INVALID_STATE = "AUTH_INVALID_STATE"
AUTH_TOKEN_BLACKLISTED = "AUTH_TOKEN_BLACKLISTED"

# ==========================================
# 課金エラー
# ==========================================
BILLING_INSUFFICIENT_BALANCE = "BILLING_INSUFFICIENT_BALANCE"
BILLING_INVALID_PRODUCT_ID = "BILLING_INVALID_PRODUCT_ID"
BILLING_INVALID_PURCHASE = "BILLING_INVALID_PURCHASE"
BILLING_DUPLICATE_TRANSACTION = "BILLING_DUPLICATE_TRANSACTION"
BILLING_TRANSACTION_NOT_FOUND = "BILLING_TRANSACTION_NOT_FOUND"
BILLING_CREDIT_NOT_FOUND = "BILLING_CREDIT_NOT_FOUND"
BILLING_INVALID_AMOUNT = "BILLING_INVALID_AMOUNT"

# ==========================================
# LLMエラー
# ==========================================
LLM_PROVIDER_NOT_FOUND = "LLM_PROVIDER_NOT_FOUND"
LLM_MODEL_NOT_FOUND = "LLM_MODEL_NOT_FOUND"
LLM_API_ERROR = "LLM_API_ERROR"
LLM_RATE_LIMIT_EXCEEDED = "LLM_RATE_LIMIT_EXCEEDED"
LLM_CONTEXT_TOO_LONG = "LLM_CONTEXT_TOO_LONG"
LLM_INVALID_REQUEST = "LLM_INVALID_REQUEST"

# ==========================================
# データベースエラー
# ==========================================
DB_CONNECTION_ERROR = "DB_CONNECTION_ERROR"
DB_QUERY_ERROR = "DB_QUERY_ERROR"
DB_INTEGRITY_ERROR = "DB_INTEGRITY_ERROR"

# ==========================================
# 外部サービスエラー
# ==========================================
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
EXTERNAL_SERVICE_TIMEOUT = "EXTERNAL_SERVICE_TIMEOUT"
EXTERNAL_SERVICE_UNAVAILABLE = "EXTERNAL_SERVICE_UNAVAILABLE"
